# Generated by Django 2.2.16 on 2020-09-12 15:22

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecard',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='basiccard',
            options={'verbose_name': 'Стандартная карточка', 'verbose_name_plural': 'Стандартные карточки'},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name': 'Колода', 'verbose_name_plural': 'Колоды'},
        ),
        migrations.AlterModelOptions(
            name='inputcard',
            options={'verbose_name': 'Карточка с вводом', 'verbose_name_plural': 'Карточки с вводом'},
        ),
        migrations.RenameField(
            model_name='inputcard',
            old_name='explanatioin',
            new_name='explanation',
        ),
        migrations.AddField(
            model_name='basecard',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Проверена карточка'),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='anki_cards.Deck', verbose_name='Колода'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='anki_cards.Deck', verbose_name='Под колода'),
        ),
        migrations.AlterField(
            model_name='inputcard',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
    ]
