# Generated by Django 2.2.16 on 2020-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0002_auto_20200912_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecard',
            old_name='text_searching',
            new_name='searched_text',
        ),
        migrations.AlterField(
            model_name='basecard',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Провереная карточка'),
        ),
    ]
