# Generated by Django 2.2.16 on 2020-09-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0003_auto_20200912_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecard',
            options={'permissions': (('editor', 'can edit cards and add cards to deck'),), 'verbose_name': 'Карточкy', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name': 'Колоду', 'verbose_name_plural': 'Колоды'},
        ),
        migrations.RemoveField(
            model_name='basecard',
            name='flag',
        ),
        migrations.AddField(
            model_name='basecard',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Публиковать'),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='anki_cards.Deck', verbose_name='Колода'),
        ),
    ]
