# Generated by Django 2.2.16 on 2020-09-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0004_auto_20200915_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputcard',
            name='basecard_ptr',
        ),
        migrations.DeleteModel(
            name='BasicCard',
        ),
        migrations.DeleteModel(
            name='InputCard',
        ),
    ]
