# Generated by Django 2.2.16 on 2020-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0005_auto_20200915_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecard',
            name='answer_card',
            field=models.TextField(default=1, verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecard',
            name='back_side',
            field=models.TextField(default=1, verbose_name='Объяснения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basecard',
            name='question',
            field=models.TextField(default=1, verbose_name='Фронтальная сторона'),
            preserve_default=False,
        ),
    ]
