# Generated by Django 2.2.16 on 2020-09-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0006_auto_20200915_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecard',
            old_name='back_side',
            new_name='back',
        ),
        migrations.RenameField(
            model_name='basecard',
            old_name='question',
            new_name='front',
        ),
        migrations.RemoveField(
            model_name='basecard',
            name='answer_card',
        ),
        migrations.AddField(
            model_name='basecard',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
    ]
