# Generated by Django 2.2.16 on 2020-09-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0008_auto_20200915_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicCard',
            fields=[
                ('basecard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anki_cards.BaseCard')),
                ('front', models.TextField(verbose_name='Фронтальная сторона')),
                ('back', models.TextField(verbose_name='Обратная строна ')),
            ],
            options={
                'verbose_name': 'Стандартная карточка',
                'verbose_name_plural': 'Стандартные карточки',
            },
            bases=('anki_cards.basecard',),
        ),
        migrations.CreateModel(
            name='InputCard',
            fields=[
                ('basecard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anki_cards.BaseCard')),
                ('front', models.TextField(verbose_name='Фронтальная сторона')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('explanation', models.TextField(verbose_name='Объяснения')),
            ],
            options={
                'verbose_name': 'Карточка с вводом',
                'verbose_name_plural': 'Карточки с вводом',
            },
            bases=('anki_cards.basecard',),
        ),
    ]
