# Generated by Django 2.2.16 on 2020-09-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0009_basiccard_inputcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecard',
            options={'permissions': (('editor', 'can edit cards and add cards to deck'),), 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterField(
            model_name='basecard',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='inputcard',
            name='answer',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
        migrations.DeleteModel(
            name='BasicCard',
        ),
    ]
