# Generated by Django 2.2.16 on 2020-09-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0010_auto_20200915_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputCard',
            new_name='BasicCard',
        ),
    ]
