# Generated by Django 2.2.16 on 2020-09-16 10:37

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0011_auto_20200915_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='anki_cards.Deck', verbose_name='Родитель'),
        ),
    ]
