# Generated by Django 2.2.11 on 2020-09-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0012_auto_20200916_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccard',
            name='answer',
            field=models.TextField(blank=True, help_text='Что укажет пользователь в поле ввода. Если пусто, то в карточке вместо поля ввода будет Кнопка "Показать ответ".', verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='basiccard',
            name='explanation',
            field=models.TextField(verbose_name='Обратная сторона'),
        ),
    ]
