# Generated by Django 2.2.11 on 2020-09-16 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anki_cards', '0015_auto_20200916_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecard',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='создано'),
        ),
        migrations.AddField(
            model_name='basecard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создано'),
        ),
    ]
