# Generated by Django 2.2.11 on 2020-09-16 15:08

from django.db import migrations
from django.utils import timezone


def fill_required_fields(apps, schema_editor):
    BaseCard = apps.get_model('anki_cards', 'BaseCard')
    DvmnUser = apps.get_model('dvmn_users', 'DvmnUser')

    BaseCard.objects.filter(created_at=None).update(created_at=timezone.now())

    author = (
        DvmnUser.objects.filter(is_superuser=True).first() or
        DvmnUser.objects.filter(is_staff=True).first() or
        DvmnUser.objects.first()
    )

    BaseCard.objects.filter(created_by=None).update(created_by=author)


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0016_auto_20200916_1807'),
        ('dvmn_users', '0036_merge_20200828_1839'),
    ]

    operations = [
        migrations.RunPython(fill_required_fields),
    ]
