# Generated by Django 2.2.11 on 2020-09-16 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0017_auto_20200916_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создано'),
        ),
    ]
