# Generated by Django 2.2.11 on 2020-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0018_auto_20200916_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='searched_text',
            field=models.TextField(blank=True, db_index=True, verbose_name='Поиск по тексту'),
        ),
    ]
