# Generated by Django 2.2.16 on 2020-09-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0085_datamigration'),
        ('challenges', '0136_module_provider'),
        ('anki_cards', '0019_auto_20200916_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecard',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='basecard',
            name='solution_enhancement_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.SolutionEnhancementTemplate', verbose_name='Расширения шаблона решения'),
        ),
    ]
