# Generated by Django 2.2.11 on 2020-09-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0020_auto_20200919_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccard',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Объяснение ответа'),
        ),
    ]
