# Generated by Django 2.2.16 on 2020-09-21 08:09

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('anki_cards', '0021_auto_20200919_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecard',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Добавьте тэги для быстрого поиска', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
    ]
