# Generated by Django 2.2.16 on 2020-09-22 19:01

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0022_basecard_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecard',
            name='searched_text',
        ),
        migrations.AlterField(
            model_name='basecard',
            name='solution_enhancement_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.SolutionEnhancementTemplate', verbose_name='Улушение из код ревью'),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Добавьте тэги для быстрого поиска', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
