# Generated by Django 2.2.16 on 2020-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0024_deck_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecard',
            name='enhancement',
            field=models.TextField(blank=True, verbose_name='Улучшение'),
        ),
    ]
