# Generated by Django 2.2.16 on 2020-09-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0027_auto_20200930_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='enhancement',
            field=models.TextField(blank=True, verbose_name='Замечание редактора'),
        ),
    ]
