# Generated by Django 2.2.16 on 2020-10-04 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0029_auto_20200930_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basecards', to=settings.AUTH_USER_MODEL, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basecards', to='challenges.Lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='solution_enhancement_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basecards', to='reviews.SolutionEnhancementTemplate', verbose_name='Улушение из код ревью'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.SlugField(max_length=64, null=True, unique=True),
        ),
    ]
