# Generated by Django 2.2.16 on 2020-10-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0030_auto_20201004_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecard',
            name='image',
        ),
    ]
