# Generated by Django 2.2.16 on 2020-10-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0031_remove_basecard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='card_status',
            field=models.CharField(blank=True, choices=[('wait', 'Ожидает проверки'), ('improvements', 'Нужны доработки'), ('approved', 'Одобрена')], db_index=True, default='wait', max_length=40, verbose_name='Статус карточки'),
        ),
    ]
