# Generated by Django 2.2.16 on 2020-10-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0032_auto_20201009_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='anki_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
