# Generated by Django 2.2.16 on 2020-10-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0033_deck_anki_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishCard',
            fields=[
                ('basecard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anki_cards.BaseCard')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('word_translation', models.CharField(max_length=100, verbose_name='Перевод слова')),
                ('phrase', models.TextField(verbose_name='Фраза (подлежащее + сказуемое)')),
                ('phrase_translation', models.TextField(verbose_name='Перевод фразы')),
                ('article_link', models.URLField(max_length=300, verbose_name='Ссылка на статью')),
            ],
            options={
                'verbose_name': 'Карточка по Английскому',
                'verbose_name_plural': 'Карточки по Английскому',
            },
            bases=('anki_cards.basecard',),
        ),
    ]
