# Generated by Django 2.2.16 on 2020-10-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0034_englishcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecard',
            name='guid',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
