# Generated by Django 2.2.16 on 2020-10-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0035_basecard_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='guid',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
