# Generated by Django 2.2.16 on 2020-10-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0036_auto_20201017_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishcard',
            name='article_link',
            field=models.URLField(blank=True, max_length=300, verbose_name='Ссылка на статью'),
        ),
        migrations.AlterField(
            model_name='englishcard',
            name='word',
            field=models.CharField(blank=True, max_length=100, verbose_name='Слово'),
        ),
    ]
