# Generated by Django 2.2.16 on 2020-10-18 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('anki_cards', '0037_auto_20201018_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basecards', to=settings.AUTH_USER_MODEL, verbose_name='Создано'),
        ),
        migrations.CreateModel(
            name='Sleng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_with_synonyms', models.CharField(max_length=200, null=True, verbose_name='Слово + синонимы')),
                ('footnote_explanation', models.TextField(verbose_name='Пояснение в сноске')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Добавьте тэги для быстрого поиска', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Сленг',
                'verbose_name_plural': 'Сленги',
            },
        ),
    ]
