# Generated by Django 2.2.16 on 2020-10-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0038_auto_20201018_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishcard',
            name='sleng',
            field=models.ManyToManyField(to='anki_cards.Sleng', verbose_name='Сленг'),
        ),
    ]
