# Generated by Django 2.2.16 on 2020-10-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0039_englishcard_sleng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='englishcard',
            old_name='sleng',
            new_name='slengs',
        ),
    ]
