# Generated by Django 2.2.16 on 2020-10-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0040_auto_20201018_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='anki_id',
        ),
        migrations.AlterField(
            model_name='englishcard',
            name='slengs',
            field=models.ManyToManyField(blank=True, to='anki_cards.Sleng', verbose_name='Сленг'),
        ),
    ]
