# Generated by Django 2.2.16 on 2020-10-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0041_auto_20201019_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='card_status',
            field=models.CharField(blank=True, choices=[('wait', 'Ожидает проверки'), ('improvements', 'Нужны доработки'), ('approved', 'Одобрена'), ('fixed', 'Исправлено')], db_index=True, default='wait', max_length=40, verbose_name='Статус карточки'),
        ),
    ]
