# Generated by Django 2.2.16 on 2020-10-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0042_auto_20201019_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishcard',
            name='acting_voice',
            field=models.FileField(blank=True, upload_to='acting_voices/'),
        ),
    ]
