# Generated by Django 2.2.11 on 2020-10-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0046_auto_20201028_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='guid',
            field=models.CharField(db_index=True, help_text='Globally unique id, almost certainly used for syncing', max_length=36, unique=True),
        ),
    ]
