# Generated by Django 2.2.16 on 2020-10-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0047_auto_20201028_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishcard',
            name='acting_voice',
            field=models.FileField(blank=True, upload_to='acting_voices'),
        ),
    ]
