# Generated by Django 2.2.17 on 2020-11-12 14:48

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0048_auto_20201031_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiccard',
            name='_explanation_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basiccard',
            name='_front_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basiccard',
            name='explanation_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='basiccard',
            name='front_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='englishcard',
            name='_phrase_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishcard',
            name='_phrase_translation_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishcard',
            name='phrase_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='englishcard',
            name='phrase_translation_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='sleng',
            name='_footnote_explanation_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleng',
            name='footnote_explanation_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='basiccard',
            name='explanation',
            field=markupfield.fields.MarkupField(blank=True, choices=[('anki_markdown', 'anki_markdown')], rendered_field=True, verbose_name='Объяснение ответа'),
        ),
        migrations.AlterField(
            model_name='basiccard',
            name='front',
            field=markupfield.fields.MarkupField(choices=[('anki_markdown', 'anki_markdown')], rendered_field=True, verbose_name='Фронтальная сторона'),
        ),
        migrations.AlterField(
            model_name='englishcard',
            name='phrase',
            field=markupfield.fields.MarkupField(choices=[('anki_markdown', 'anki_markdown')], rendered_field=True, verbose_name='Фраза (подлежащее + сказуемое)'),
        ),
        migrations.AlterField(
            model_name='englishcard',
            name='phrase_translation',
            field=markupfield.fields.MarkupField(choices=[('anki_markdown', 'anki_markdown')], rendered_field=True, verbose_name='Перевод фразы'),
        ),
        migrations.AlterField(
            model_name='sleng',
            name='footnote_explanation',
            field=markupfield.fields.MarkupField(choices=[('anki_markdown', 'anki_markdown')], rendered_field=True, verbose_name='Пояснение в сноске'),
        ),
    ]
