# Generated by Django 2.2.17 on 2020-11-12 15:00

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0049_auto_20201112_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccard',
            name='explanation',
            field=markupfield.fields.MarkupField(blank=True, rendered_field=True, verbose_name='Объяснение ответа'),
        ),
        migrations.AlterField(
            model_name='basiccard',
            name='explanation_markup_type',
            field=models.CharField(choices=[('', '--'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='basiccard',
            name='front',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='Фронтальная сторона'),
        ),
        migrations.AlterField(
            model_name='basiccard',
            name='front_markup_type',
            field=models.CharField(choices=[('', '--'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='englishcard',
            name='phrase',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='Фраза (подлежащее + сказуемое)'),
        ),
        migrations.AlterField(
            model_name='englishcard',
            name='phrase_markup_type',
            field=models.CharField(choices=[('', '--'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='englishcard',
            name='phrase_translation',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='Перевод фразы'),
        ),
        migrations.AlterField(
            model_name='englishcard',
            name='phrase_translation_markup_type',
            field=models.CharField(choices=[('', '--'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='sleng',
            name='footnote_explanation',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='Пояснение в сноске'),
        ),
        migrations.AlterField(
            model_name='sleng',
            name='footnote_explanation_markup_type',
            field=models.CharField(choices=[('', '--'), ('anki_markdown', 'anki_markdown')], default='anki_markdown', editable=False, max_length=30),
        ),
    ]
