# Generated by Django 2.2.17 on 2020-11-12 15:05
from tqdm import tqdm

from django.db import migrations


def prerender_markdown(apps, schema_editor):
    BasicCard = apps.get_model('anki_cards', 'BasicCard')
    EnglishCard = apps.get_model('anki_cards', 'EnglishCard')
    Sleng = apps.get_model('anki_cards', 'Sleng')

    basic_cards_query = BasicCard.objects.all()
    for card in tqdm(basic_cards_query, desc='Prerender BasicCard markdown fields', total=basic_cards_query.count()):
        card.save()  # render markdown with pre_save handler in django-markupfield app

    english_cards_query = EnglishCard.objects.all()
    for card in tqdm(english_cards_query, desc='Prerender EnglishCard markdown fields', total=english_cards_query.count()):
        card.save()  # render markdown with pre_save handler in django-markupfield app

    sleng_query = Sleng.objects.all()
    for sleng in tqdm(sleng_query, desc='Prerender Sleng markdown fields', total=sleng_query.count()):
        sleng.save()  # render markdown with pre_save handler in django-markupfield app


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('anki_cards', '0050_auto_20201112_1800'),
    ]

    operations = [
        migrations.RunPython(prerender_markdown),
    ]
