# Generated by Django 2.2.16 on 2020-11-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0051_auto_20201112_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='card_status',
            field=models.CharField(blank=True, choices=[('wait', 'Ожидает проверки'), ('improvements', 'Нужны доработки'), ('fixed', 'Исправлено'), ('approved', 'Одобрена')], db_index=True, default='wait', max_length=40, verbose_name='Этап модерации'),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='enhancement',
            field=models.TextField(blank=True, default='Отсутствуют', verbose_name='Замечания редактора'),
        ),
    ]
