# Generated by Django 2.2.16 on 2020-11-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0052_auto_20201113_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecard',
            name='enhancement',
        ),
        migrations.AddField(
            model_name='basecard',
            name='moderator_notes',
            field=models.TextField(blank=True, verbose_name='Замечания редактора'),
        ),
        migrations.AlterField(
            model_name='basecard',
            name='card_status',
            field=models.CharField(choices=[('wait', 'Ожидает проверки'), ('improvements', 'Нужны доработки'), ('fixed', 'Исправлено'), ('approved', 'Одобрена')], db_index=True, default='wait', max_length=40, verbose_name='Этап модерации'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='sleng',
            name='word_with_synonyms',
            field=models.CharField(max_length=200, verbose_name='Слово + синонимы'),
        ),
    ]
