# Generated by Django 2.2.17 on 2020-11-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0053_auto_20201113_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecard',
            name='card_status',
            field=models.CharField(choices=[('improvements', 'Нужны доработки'), ('wait', 'Ожидает проверки'), ('approved', 'Одобрена')], db_index=True, default='wait', max_length=40, verbose_name='Этап модерации'),
        ),
    ]
