# Generated by Django 2.2.17 on 2020-11-18 15:05

from django.db import migrations


def replace_moderation_status_fixed_with_wait(apps, schema_editor):
    BaseCard = apps.get_model('anki_cards', 'BaseCard')
    BaseCard.objects.filter(card_status='fixed').update(card_status='wait')


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0054_auto_20201118_1805'),
    ]

    operations = [
        migrations.RunPython(replace_moderation_status_fixed_with_wait),
    ]
