# Generated by Django 2.2.17 on 2020-11-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki_cards', '0055_auto_20201118_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basecard',
            old_name='card_status',
            new_name='moderation_status',
        ),
    ]
